### PR TITLE
fix: ssr exception in runtime

### LINKED ISSUE #18: On SSR gives `ReferenceError`s for window and document
The first thing is first; it works on SSR.

But gives console errors on page loads.

At first load of the app; it gives `ReferenceError: window is not defined`. Full output: 

```
ReferenceError: window is not defined
    at Object.Z8CG (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:159033:3)
    at __webpack_require__ (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:20:30)
    at new StickyDirective (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:150795:9)
    at createClass (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:79786:20)
    at createDirectiveInstance (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:79606:22)
    at createViewNodes (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:90886:38)
    at callViewAction (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:91336:13)
    at execComponentViewsAction (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:91241:13)
    at createViewNodes (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:90915:5)
    at createRootView (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:90758:5)
```

When surfing between pages after the app is loaded, it gives `ERROR ReferenceError: document is not defined`. Full output:

```
ERROR ReferenceError: document is not defined
    at StickyDirective.generateSentinelElement (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:150948:28)
    at StickyDirective.putSentinel (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:150966:31)
    at StickyDirective.ngAfterViewInit (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:150859:14)
    at callProviderLifecycles (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:80127:18)
    at callElementProvidersLifecycles (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:80092:13)
    at callLifecycleHooksChildrenFirst (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:80074:29)
    at checkAndUpdateView (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:90957:5)
    at callViewAction (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:91313:21)
    at execComponentViewsAction (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:91241:13)
    at checkAndUpdateView (/Volumes/WD_RAID/Documents/Projects/Web/medyaeli website/dist/server/main.js:90954:5)
```

### PR DESCRIPTION
**Pull request by osnoser1**
## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] angular.io application / infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

In SSR runtime occurs two exceptions: window and document is not defined.

Issue Number: #18 

## What is the new behavior?

All exceptions are gone in ssr.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

This PR has two commits:

* The first prepare the application for be executed in ssr.
* The second commit apply the fix. This consists is to update the IntersectionObserver polyfill for avoid the `window` exception, not create the IntersectionObserver instance in ssr because it isn't work, and inject the `document` by angular because in ssr that it is created by domino library that angular uses since version 6 .

Closes #18

### CODE REVIEW

**Comment by dianjuar** [comment]
@osnoser1 can you please describe the PR?
You can use the Angular PR template to do that. 

I have no experience on this field and would be nice to have an explanation instead of reading code to understand what was wrong

**Comment by osnoser1** [comment]
Done @dianjuar 👍🏼

File: projects/sticky-directive/src/lib/sticky.directive.ts [hunk 1]
```diff
@@ -128,6 +134,10 @@ export class StickyDirective implements OnInit, AfterViewInit {
    * Start listening to the scroll event on the container element
    */
   private setObserver() {
+    if (isPlatformServer(this.platformId)) {
```
Comment (dianjuar) [inline projects/sticky-directive/src/lib/sticky.directive.ts]: Can you explain a little about this.

We think that works as follow:
- If it's on server side, does nothing
- If i'ts on the browser starts listening

> We know almost nothing about SSR

File: package.json [hunk 2]
```diff
@@ -39,9 +43,13 @@
...
     "@angular/platform-browser": "~7.2.1",
     "@angular/platform-browser-dynamic": "~7.2.1",
+    "@angular/platform-server": "~7.2.1",
     "@angular/router": "~7.2.1",
+    "@nguniversal/express-engine": "~7.1.1",
+    "@nguniversal/module-map-ngfactory-loader": "~7.1.1",
     "core-js": "^2.6.2",
-    "intersection-observer": "^0.5.1",
+    "express": "^4.15.2",
+    "intersection-observer": "^0.7.0",
```
Comment (dianjuar) [inline package.json]: This is needed because they add some fixes that are needed for the SSR fix?

File: angular.json [hunk 3]
```diff
@@ -17,7 +17,7 @@
         "build": {
           "builder": "@angular-devkit/build-angular:browser",
           "options": {
-            "outputPath": "dist/ngx-sticky-demo",
+            "outputPath": "dist/browser",
```
[the remark this answers is not in the document]
Comment (osnoser1) [reply angular.json]: It's a automatic change of the schematics. This change is because two compilations are now executed, one is saved in the `server` folder, and the other is saved in the `browser` folder. It's just a way of differences both compilations, if you don't like it I can reverse that change. 😄

File: projects/sticky-directive/src/lib/sticky.directive.ts (hunk 1 above)
Comment (osnoser1) [reply projects/sticky-directive/src/lib/sticky.directive.ts]: That is correct, that is how it works.

File: package.json (hunk 2 above)
Comment (osnoser1) [reply package.json]: This is to avoid the `window is not defined` exception. They add fixes for the SSR fix. 😄

**Comment by dianjuar** [comment]
@osnoser1 Your PR is just awesome!

I will run Unit Test and Sonar Analysis (I now, I now, the CI should be doing this)and tell you how it went.

If nothing happens I will integrate your PR.


### THANK   YOU!!!!!

File: projects/sticky-directive/src/lib/sticky.directive.ts (hunk 1 above)
[the remark this answers is not in the document]
Comment (osnoser1) [reply projects/sticky-directive/src/lib/sticky.directive.ts]: Done... 👍🏼😄
